"""
Common functions used by the rest of the software.
Constants (pathnames) are also defined here.
"""
import os
import datetime
import re

# Directory where the data files are stored
SOURCE_FOLDER = '/mnt/rtc-share/RTC/GUI/ngs2_int64_delays/201'

# Directory where the files will be copied to
DATA_FOLDER = './data'

# The data files generated by the memory dump program have names of the form <root><n>.txt,
# where <root> is any of the files in the list below and <n> is 1 or 2.
FILE_ROOT_NAMES = (
    "dm0a_a",
    "dm0a_b",
    "dm0b_a",
    "dm0b_b",
    "dm4a_a",
    "dm4a_b",
    "dm4b_a",
    "dm4b_b",
    "dm9_a",
    "dm9_b",
)


def get_file_list() -> list:
    """
    Return the list of files names generated by the diag21k memory dump script.
    :return: list of file names
    """
    output_list = []
    for n in [1, 2]:
        for root in FILE_ROOT_NAMES:
            output_list.append(f'{root}{n}.txt')
    return output_list


def get_source_file_list() -> list:
    """
    Get the list of full names (including DATA_PATH) generated by the memory dump script.
    :return: list of file names
    """
    return [os.path.join(SOURCE_FOLDER, x) for x in get_file_list()]


def get_destination_file_list(directory=DATA_FOLDER):
    """
    The destination file names is the same as the source file names, except that
    they will be stored in the destination directory, and they will have a timestamp
    based on the creation time of the files generated by the memory dump script.
    The time stamp of the first file will be used for all files to avoid confusion.
    :return: list of file names
    """
    output_list = []
    ts = None
    for file_name in get_source_file_list():
        if ts is None:
            ts = datetime.datetime.fromtimestamp(os.path.getctime(file_name)).strftime('%Y%m%d%H%M%S')
        base_name, extension = os.path.splitext(os.path.basename(file_name))
        output_list.append(os.path.join(directory, f'{base_name}_{ts}{extension}'))
    return output_list


def get_process_file_list(timestamp: str, directory=DATA_FOLDER) -> list:
    """
    Return the name of the files that match a given timestamp in the local data directory.
    :param: timestamp: timestamp of the form <date><time> (e.g. 20220922180942)
    :param: directory: destination directory (default=DATA_FOLDER).
    :return: list of files
    """
    return [os.path.join(directory,x) for x in os.listdir(directory) if re.search(timestamp, x)]


if __name__ == '__main__':
    # print(get_file_list())
    # print(get_source_file_list())
    # print(get_destination_file_list())
    print(get_process_file_list('20220928114409'))
    pass
